### ISSUE TITLE
Link to Theano isn't working for me. Maybe add this to the readme?

### ISSUE THREAD

**Issue by maccam912** [dtarlow/Machine-March-Madness#1]
I see you can still get it with 'easy_install Theano' or downloading it from http://pypi.python.org/pypi/Theano or the repo on github. Just a heads up. I don't use git or github often so I wasn't sure if the issues section was the place to point this out or not.

**Comment by dtarlow** [comment]
Hi, thanks for the report.  It looks like the Theano site is down, and it has been reported on the Theano google group: 
http://groups.google.com/group/theano-users/browse_thread/thread/f7c1f00e17dfa3f9

I'll update the README to include your note.  Thanks!
